// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2sxrFcHRajZb-X-72UA3Um5tLpS39npw',
    appId: '1:527014973576:web:dfa2746196866592228f3d',
    messagingSenderId: '527014973576',
    projectId: 'setra-60c09',
    authDomain: 'setra-60c09.firebaseapp.com',
    storageBucket: 'setra-60c09.firebasestorage.app',
    measurementId: 'G-6EL8LW0HX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR9vENJn8KbSNe3QKU2oEqXvDipw3qNsI',
    appId: '1:527014973576:android:00e13a89c9e653f4228f3d',
    messagingSenderId: '527014973576',
    projectId: 'setra-60c09',
    storageBucket: 'setra-60c09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKrbUySMj0iXyJyD88zQBKlQ27cbd608',
    appId: '1:527014973576:ios:9e12c3016485c68b228f3d',
    messagingSenderId: '527014973576',
    projectId: 'setra-60c09',
    storageBucket: 'setra-60c09.firebasestorage.app',
    iosBundleId: 'com.example.setra',
  );
}
